<html>
<head>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

</head>
<body>
    <h1>ECalTest - Calendar</h1>
   
    <div class="well">
    <a class="btn btn-default" href="/calendar" role="button">Calendar</a>
    <a class="btn btn-default" href="#" role="button">Appointment</a>
    <a class="btn btn-default" href="#" role="button">Log</a>
    </div>

    <form action="/calendar/create" method="post">
    <div class="input-group">
      <input type="text" class="form-control" name="name" placeholder="Calendar name">
      <span class="input-group-btn">
        <input class="btn btn-default" type="submit" value="Create"/>
      </span>
    </div><!-- /input-group -->
    
    </form>
    

<table class="table">
<tr>
<th>id<th>
<th></th>

</tr>
<?php foreach ($calendars as $calendar) : ?>
<tr>
<form action="/calendar/update" method="post">
    <td><?php echo $calendar->id ?></td>
    <td>
    
    <input name="name" value="<?php echo $calendar->name ?>" />
    <input type="hidden" name="id" value="<?php echo $calendar->id ?>" />
    
    </td>
    <td>
    
    <button type="submit" class="btn btn-default">Update</button>
    <a class="btn btn-default" href="/calendar/remove?id=<?php echo $calendar->id?>" role="button">Remove</a>
    <a class="btn btn-default" href="/appointment?calendar_id=<?php echo $calendar->id?>" role="button">Appointments</a>
    </td>
</form>
</tr>
<?php endforeach; ?>
</table>


</body>
</html>