<html>
<head>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

</head>
<body>
    <h1>ECalTest</h1>
   
    <a class="btn btn-default" href="/calendar" role="button">Calendar</a>
    <a class="btn btn-default" href="#" role="button">Appointment</a>
    <a class="btn btn-default" href="#" role="button">Log</a>

</body>
</html>